FROM node:latest
RUN mkdir -p /server
WORKDIR /server
COPY ./package*.json ./
RUN apt-get update -y
RUN apt-get install npm -y
COPY . /server
RUN npm install
RUN npm install cors --save
COPY . /server/
EXPOSE 5000
CMD ["npm", "start"]

# a similar variant also works
