version: '3'

services:
  database:
    build:
      context: ./data
      dockerfile: Dockerfile
    image: my_database_image
    container_name: my_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: lumine
      MYSQL_PASSWORD: lumine
    ports:
      - "3307:3306"
    volumes:
      - ./data/my_cache:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: my_server_image
    container_name: my_server
    restart: always
    ports:
      - "5000:5000"
    working_dir: /server
    command: npm start
    tty: true
    depends_on:
      - database

  # nginx:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   image: my_client_image
  #   container_name: my_client
  #   restart: always
  #   tty: true
  #   ports:
  #     - "80:8080"
  #   working_dir: /client
  #   depends_on:
  #     - server

networks:
  et-network:
    driver: bridge
